version: '3.7'

services:
  app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: ${PORT}
    ports:
      - '11001:3000'
    volumes:
      - ./src:/app/src
      - ./.svelte-kit:/app/.svelte-kit
      - ./static:/app/static
      - ./.env:/app/.env